### ISSUE TITLE
modul mip on ESP32

### ISSUE THREAD

**Issue by appi1** [mc0110/wifimanager#3]
Hello
During the installation I encounter problems with the command:
install mip
the ESP32 is connected to the Wifi.
Question: is there a "mip" module for the ESP32?

**Comment by mc0110** [comment]
Hi, 
[mip module](https://docs.micropython.org/en/latest/reference/packages.html) is a standard module, but the right command for loading a module is 'import'. Did you use 'import' or 'install'?

**Comment by appi1** [comment]
hi 

yeah, import mip don't work.  import time as an example works.

>>> import mip
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'mip'
>>> import time
>>>

**Comment by mc0110** [comment]
I assume you are using an older version of Micropython. Unfortunately, at the moment the documentation is updated more quickly than the 'stable' versions. In the June version, a number of functions do not yet exist, but can be found in the documentation. mip is the successor to upip - see [Nightly builds](https://micropython.org/download/esp32/) for a new version.

**Comment by 7wells** [comment]
I confirm that `import mip` works with the latest nightly of mPython.
