### ISSUE TITLE
Trigger ESP32 update from repo?

### ISSUE THREAD

**Issue by 7wells** [mc0110/wifimanager#5]
Hi Magnus,

Do you have an example how this very nice tool you created could be used in connection with a personal e.g. GitHub repo? Could the wifimanager check the repo and do something triggered by a certain value of a variable in that repo code? Could it thus be used to update the ESP32 automatically if a code update happened?

I also thought about WOL and magic packets and wondered if such a mechanism could be used similarly to trigger an update of the ESP32 via  wifimanager?

PS and a bit OT (sorry):
Do you know these ESP32 breakout boards? Could be useful, so I just ordered some:
https://www.amazon.de/gp/aw/d/B0BJF1W86K

There are different of these adapters that don't fit all ESP32s, i.e. they have slightly different dimensions, some only fitting ESP32s with mounting holes (like mine).

**Comment by mc0110** [comment]
Hi,

I hadn't thought about the Wifimanager checking the repo and doing the update on its own. But that is possible without any problems. What is important is that an update (even from several repos) is possible via a function that you can simply call. The mechanics can be found in cred.py. Even with the initial upload, the main.py only calls this function update_repor() in cred.py. Of course, you can use this for your own repos as well. You just have to adapt cred.py to the repo. An example is inetbox2mqtt, which now also uses this functionality.

About your PS
I have no experience with these boards - but they don't look bad. Should actually work.

**Comment by mc0110** [comment]
I have now implemented the function. It can even be set to happen automatically (at system start). Also, release numbers are introduced so that updates only happen when there are changes in the repo. You can easily use it for your own GITHUB repo by cloning wifimanager or even better by pulling the data from both repos. I would close the issue with this.

**Comment by 7wells** [comment]
@mc0110 
Sorry to bother you once more, but I still miss a link how to actually use wifimanager and inetbox2mqtt in practice together. You have already provided lots of very detailed and helpful information on both repos, but I seem to be not smart enough to get the full picture, i.e. how to setup what (first) on my ESP32 and how I could use my own (cloned and maybe modified) repo of I want to change something. Is there maybe a good place where users could exchange their questions and experience with both tools? Thank you so much for your patience with me! 😊

**Comment by mc0110** [comment]
Hi,
there are no stupid questions, only unfortunately too often unkind answers. I hope my answer doesn't fall into that category. 

So I'll try to work through it in order:
- the wifimanager is completely integrated in inetbox2mqtt, nothing to do there
- the wifimanager can be used for any repo, so also for yours, no matter what they contain (clones, own developments)
- You have to take the files from the wifimanager repo and adapt cred.py to the files you want to load and manage the release no in main.py and release.py for your repo.
- What I already have running as a prototype is a uPython firmware that already contains the wifimanager. This means that it already starts after flashing the firmware. The idea is then to specify the repo in the web frontend from which the software is to be loaded after the Wifi connection is established.

I hope I have been able to provide a little more transparency and have not created any new confusion.

**Comment by 7wells** [comment]
Hi Magnus, I hope you are well!

Thanks a lot for your recent explanations. Now that I wanted to occupy myself again with the topic, I stumbled over some further questions and hope you can help me:

Can you have both firmware and inetbox2mqtt updated regularly and automatically?

How would you check which uPython firmware version is the latest available with which your inetbox2mqtt (or other project) works? I remember your hint that it works only from a specific nightly firmware build version onwards.

Or is this not possible, because too many things could go wrong? (I would not automatically update my Endeavour OS, but maybe that's not comparable with IoT and uPython?)

Have a nice Sunday! 😀

**Comment by mc0110** [comment]
Hi my friend,

yes, I'm fine! Thanks for asking.

A short update on the current status of the project:
If I remember correctly, you are using the ESP32. So here is the explanation for this chip.
The ESP32 just doesn't have enough main memory to hold the whole project with all the addons in memory. The solution that works is to pre-compile the code and flash it together with the firmware. For this I made the following compromise.
Everything that is used for the web frontend as well as the libraries for the addons, conversions, etc. are contained in the firmware. All other libraries are in the file system and can therefore be changed. 
The recommended procedure is therefore to flash the project firmware (version: 2.0.1). This is fully executable, but can also be provided with updates of the mutable modules at a later date. Unfortunately, it is no longer possible to use the "small" 4M ESP32 with the normal micropython versions. 

Is this explanation sufficient for you?

**Comment by 7wells** [comment]
>Unfortunately, it is no longer possible to use the "small" 4M ESP32 with the normal micropython versions.

Does it mean that U cannot use your latest inetbox2mqtt version on my ESP32? I'm not sure how much memory it has but ask to be prepared. 😉 I would then rather stick to a version of inetbox2mqtt that runs on my ESP32. I really only need UART-LIN communication with my Truma incl. MQTT with Home Assistant. All other things are "nice to have" for me but not essential.

**Comment by mc0110** [comment]
I don't really understand your point. You need less than 5 minutes to flash the image onto your ESP32. What is problematic about that? The additional features are there to simplify the initial operation or, in case of problems, the troubleshooting. If I remember correctly, the initial setup was not that easy for you either. Of course, you are free to extract the routines you need from the repo.

**Comment by mc0110** [comment]
If your system is already running to your contentment, I don't recommend the update. Leave it as it is. Never touch a running system.

**Comment by 7wells** [comment]
You are right, of course! 😀 It's a bit of FOMO on my side. ☺️
